#!/usr/bin/env python3
"""Generate Fluent-native steady-run journals with durable text logging.

The generated journal is executed by Fluent, not by a Python iteration loop.
It starts a native transcript before the solve, prints residuals on every
iteration, and exports Fluent's retained residual history after the native
iteration command returns.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PureWindowsPath


def _fluent_path(value: str, *, label: str) -> str:
    """Validate a Windows-local absolute path and render it for Fluent TUI."""

    raw = str(value).strip()
    if not raw:
        raise ValueError(f"{label} must not be empty")
    path = PureWindowsPath(raw)
    if not path.is_absolute() or not path.drive:
        raise ValueError(
            f"{label} must be an absolute path on the Fluent Windows host, "
            rf"for example C:\FluentRuns\case-01\run.trn; got {raw!r}"
        )
    rendered = path.as_posix()
    if '"' in rendered or "\n" in rendered or "\r" in rendered:
        raise ValueError(f"{label} contains characters that are unsafe in a Fluent journal")
    return rendered


@dataclass(frozen=True)
class SteadyNativeRunJournal:
    """Inputs for one Fluent-owned steady iteration command."""

    iterations: int
    transcript_file: str
    residual_file: str
    residual_history_size: int | None = None
    plot_residuals: bool = True

    def validate(self) -> None:
        if self.iterations <= 0:
            raise ValueError("iterations must be greater than zero")
        if self.residual_history_size is not None and self.residual_history_size <= 0:
            raise ValueError("residual_history_size must be greater than zero when supplied")
        _fluent_path(self.transcript_file, label="transcript_file")
        _fluent_path(self.residual_file, label="residual_file")


def render_steady_native_run_journal(config: SteadyNativeRunJournal) -> str:
    """Return a Fluent journal that owns the run and its text evidence.

    The transcript is the live, progressively written artifact.  The dedicated
    residual file is a snapshot of Fluent's retained residual history and is
    produced after ``solve/iterate`` returns, whether normally or after an
    operator interrupt that returns control to the journal.
    """

    config.validate()
    transcript = _fluent_path(config.transcript_file, label="transcript_file")
    residual = _fluent_path(config.residual_file, label="residual_file")

    lines = [
        "; Generated by PyAnsys/scripts/setup/generate_native_run_journal.py",
        "; Run this only after the intended case is loaded and initialized.",
        "; Fluent owns the iteration command; Python is not in the run loop.",
        "/file/confirm-overwrite? no",
        f'/file/start-transcript "{transcript}"',
        "/solve/monitors/residual/print? yes",
        f"/solve/monitors/residual/plot? {'yes' if config.plot_residuals else 'no'}",
    ]
    if config.residual_history_size is not None:
        lines.append(f"/solve/monitors/residual/n-save {config.residual_history_size}")
    lines.extend(
        [
            f"/solve/iterate {config.iterations}",
            f'/plot/residuals-set/plot-to-file "{residual}"',
            "/plot/residuals",
            "/plot/residuals-set/end-plot-to-file",
            "/file/stop-transcript",
            "; Native run journal finished. Fluent remains open.",
        ]
    )
    return "\n".join(lines) + "\n"
