#!/usr/bin/env python3
"""Submit one version-pinned stage to the local Fluent host-worker spool."""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from pyansys_fluent.job_protocol import (  # noqa: E402
    FilesystemJobSpool,
    JobSpec,
    ProtocolValidationError,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Submit a read-only job to a running local Fluent host worker. The "
            "current worker boot ID and Fluent generation are captured by "
            "default to prevent execution against a different process."
        )
    )
    parser.add_argument(
        "--work-dir",
        default=str(PROJECT_ROOT / "output" / "fluent_host_worker"),
        help="Runtime directory used by fluent_host_worker.py.",
    )
    parser.add_argument(
        "--stage",
        choices=("health_check", "case_identity_probe"),
        default="health_check",
        help="Read-only stage to execute. Default: health_check.",
    )
    parser.add_argument(
        "--job-id",
        default="",
        help="Optional stable job ID. A stage-prefixed ID is generated by default.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="Total stage timeout in seconds.",
    )
    parser.add_argument(
        "--allow-any-generation",
        action="store_true",
        help="Do not pin the job to the currently reported worker generation.",
    )
    parser.add_argument(
        "--expected-worker-boot-id",
        default="",
        help="Override the worker boot ID captured from host-worker-status.json.",
    )
    parser.add_argument(
        "--expected-generation",
        type=int,
        default=None,
        help="Override the Fluent generation captured from host-worker-status.json.",
    )
    parser.add_argument(
        "--case-path",
        default="",
        help="Absolute source .cas.h5/.cas.gz/.cas path for case_identity_probe.",
    )
    parser.add_argument(
        "--expected-file-size",
        type=int,
        default=None,
        help="Optional expected source case size in bytes.",
    )
    parser.add_argument(
        "--expected-sha256",
        default="",
        help="Optional expected source case SHA-256 digest.",
    )
    parser.add_argument(
        "--compute-sha256",
        action="store_true",
        help="Record a SHA-256 digest even when no expected digest is supplied.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    work_dir = Path(args.work_dir).expanduser().resolve()
    status_path = work_dir / "host-worker-status.json"
    try:
        status = json.loads(status_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"Cannot read host-worker status {status_path}: {exc}", file=sys.stderr)
        return 2

    if status.get("state") != "running":
        print(
            f"Host worker is not running; observed state={status.get('state')!r}",
            file=sys.stderr,
        )
        return 2

    boot_id = status.get("worker_boot_id")
    generation = status.get("generation")
    if not isinstance(boot_id, str) or not boot_id:
        print("Host-worker status has no valid worker_boot_id.", file=sys.stderr)
        return 2
    if isinstance(generation, bool) or not isinstance(generation, int) or generation <= 0:
        print("Host-worker status has no valid Fluent generation.", file=sys.stderr)
        return 2
    if args.allow_any_generation and (
        args.expected_worker_boot_id.strip()
        or args.expected_generation is not None
    ):
        print(
            "--allow-any-generation cannot be combined with an expected "
            "worker boot ID or generation override.",
            file=sys.stderr,
        )
        return 2
    if args.stage == "case_identity_probe" and args.allow_any_generation:
        print(
            "case_identity_probe must be pinned to a worker boot and generation.",
            file=sys.stderr,
        )
        return 2
    if args.stage == "case_identity_probe" and not args.case_path.strip():
        print("case_identity_probe requires --case-path.", file=sys.stderr)
        return 2
    if args.stage == "health_check" and (
        args.case_path.strip()
        or args.expected_file_size is not None
        or args.expected_sha256.strip()
        or args.compute_sha256
    ):
        print(
            "Case input arguments are valid only for case_identity_probe.",
            file=sys.stderr,
        )
        return 2

    prefix = "health" if args.stage == "health_check" else "case-probe"
    job_id = args.job_id.strip() or f"{prefix}-{uuid.uuid4().hex}"
    expected_boot_id = args.expected_worker_boot_id.strip() or boot_id
    expected_generation = (
        args.expected_generation
        if args.expected_generation is not None
        else generation
    )
    spec = JobSpec(
        job_id=job_id,
        stage_type=args.stage,
        timeout_seconds=args.timeout,
        expected_worker_boot_id=(
            None if args.allow_any_generation else expected_boot_id
        ),
        expected_fluent_generation=(
            None if args.allow_any_generation else expected_generation
        ),
        case_path=args.case_path.strip() or None,
        expected_file_size_bytes=args.expected_file_size,
        expected_sha256=args.expected_sha256.strip() or None,
        compute_sha256=args.compute_sha256,
    )
    try:
        path = FilesystemJobSpool(work_dir).submit(spec)
    except (FileExistsError, ProtocolValidationError, OSError) as exc:
        print(f"Job submission failed: {exc}", file=sys.stderr)
        return 1

    print(f"Submitted {spec.stage_type} job {spec.job_id}")
    print(f"Incoming file: {path}")
    print(f"Expected worker boot ID: {spec.expected_worker_boot_id}")
    print(f"Expected Fluent generation: {spec.expected_fluent_generation}")
    if spec.case_path is not None:
        print(f"Requested case path: {spec.case_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
