#!/usr/bin/env python3
"""Submit one version-pinned stage to the local Fluent host-worker spool."""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from pyansys_fluent.job_protocol import (  # noqa: E402
    FilesystemJobSpool,
    JobSpec,
    ProtocolValidationError,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Submit a job to a running local Fluent host worker. The current "
            "worker boot ID and Fluent generation are captured by default to "
            "prevent execution against an unintended process."
        )
    )
    parser.add_argument(
        "--work-dir",
        default=str(PROJECT_ROOT / "output" / "fluent_host_worker"),
        help="Runtime directory used by fluent_host_worker.py.",
    )
    parser.add_argument(
        "--stage",
        choices=("health_check", "case_identity_probe", "resumable_run"),
        default="health_check",
        help="Stage to execute. Default: health_check.",
    )
    parser.add_argument(
        "--job-id",
        default="",
        help="Optional stable job ID. A stage-prefixed ID is generated by default.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="Total stage timeout in seconds.",
    )
    parser.add_argument(
        "--allow-any-generation",
        action="store_true",
        help="Do not pin the job to the currently reported worker generation.",
    )
    parser.add_argument(
        "--expected-worker-boot-id",
        default="",
        help="Override the worker boot ID captured from host-worker-status.json.",
    )
    parser.add_argument(
        "--expected-generation",
        type=int,
        default=None,
        help="Override the Fluent generation captured from host-worker-status.json.",
    )
    parser.add_argument(
        "--case-path",
        default="",
        help="Absolute source .cas.h5/.cas.gz/.cas path for case_identity_probe.",
    )
    parser.add_argument(
        "--expected-file-size",
        type=int,
        default=None,
        help="Optional expected source case size in bytes.",
    )
    parser.add_argument(
        "--expected-sha256",
        default="",
        help="Optional expected source case SHA-256 digest.",
    )
    parser.add_argument(
        "--compute-sha256",
        action="store_true",
        help="Record a SHA-256 digest even when no expected digest is supplied.",
    )
    parser.add_argument(
        "--total-iterations",
        type=int,
        default=None,
        help="Total iteration target for resumable_run.",
    )
    parser.add_argument(
        "--chunk-iterations",
        type=int,
        default=None,
        help="Iterations per committed checkpoint for resumable_run.",
    )
    parser.add_argument(
        "--command-timeout",
        type=float,
        default=None,
        help="Maximum seconds for one Fluent command in resumable_run.",
    )
    parser.add_argument(
        "--max-resume-attempts",
        type=int,
        default=None,
        help="Maximum fresh-generation retries after the initial run attempt.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    work_dir = Path(args.work_dir).expanduser().resolve()
    status_path = work_dir / "host-worker-status.json"
    try:
        status = json.loads(status_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"Cannot read host-worker status {status_path}: {exc}", file=sys.stderr)
        return 2

    if status.get("state") != "running":
        print(
            f"Host worker is not running; observed state={status.get('state')!r}",
            file=sys.stderr,
        )
        return 2

    boot_id = status.get("worker_boot_id")
    generation = status.get("generation")
    if not isinstance(boot_id, str) or not boot_id:
        print("Host-worker status has no valid worker_boot_id.", file=sys.stderr)
        return 2
    if isinstance(generation, bool) or not isinstance(generation, int) or generation <= 0:
        print("Host-worker status has no valid Fluent generation.", file=sys.stderr)
        return 2
    if args.allow_any_generation and (
        args.expected_worker_boot_id.strip()
        or args.expected_generation is not None
    ):
        print(
            "--allow-any-generation cannot be combined with an expected "
            "worker boot ID or generation override.",
            file=sys.stderr,
        )
        return 2
    if (
        args.stage in {"case_identity_probe", "resumable_run"}
        and args.allow_any_generation
    ):
        print(
            f"{args.stage} must be pinned to a worker boot and generation.",
            file=sys.stderr,
        )
        return 2
    if (
        args.stage in {"case_identity_probe", "resumable_run"}
        and not args.case_path.strip()
    ):
        print(f"{args.stage} requires --case-path.", file=sys.stderr)
        return 2
    if args.stage == "health_check" and (
        args.case_path.strip()
        or args.expected_file_size is not None
        or args.expected_sha256.strip()
        or args.compute_sha256
        or args.total_iterations is not None
        or args.chunk_iterations is not None
        or args.command_timeout is not None
        or args.max_resume_attempts is not None
    ):
        print(
            "Case and run input arguments are not valid for health_check.",
            file=sys.stderr,
        )
        return 2
    if args.stage == "case_identity_probe" and any(
        value is not None
        for value in (
            args.total_iterations,
            args.chunk_iterations,
            args.command_timeout,
            args.max_resume_attempts,
        )
    ):
        print(
            "Run input arguments are valid only for resumable_run.",
            file=sys.stderr,
        )
        return 2
    if args.stage == "resumable_run" and any(
        value is None
        for value in (
            args.total_iterations,
            args.chunk_iterations,
            args.command_timeout,
            args.max_resume_attempts,
        )
    ):
        print(
            "resumable_run requires --total-iterations, --chunk-iterations, "
            "--command-timeout, and --max-resume-attempts.",
            file=sys.stderr,
        )
        return 2

    prefix = {
        "health_check": "health",
        "case_identity_probe": "case-probe",
        "resumable_run": "run",
    }[args.stage]
    job_id = args.job_id.strip() or f"{prefix}-{uuid.uuid4().hex}"
    expected_boot_id = args.expected_worker_boot_id.strip() or boot_id
    expected_generation = (
        args.expected_generation
        if args.expected_generation is not None
        else generation
    )
    spec = JobSpec(
        job_id=job_id,
        stage_type=args.stage,
        timeout_seconds=args.timeout,
        expected_worker_boot_id=(
            None if args.allow_any_generation else expected_boot_id
        ),
        expected_fluent_generation=(
            None if args.allow_any_generation else expected_generation
        ),
        case_path=args.case_path.strip() or None,
        expected_file_size_bytes=args.expected_file_size,
        expected_sha256=args.expected_sha256.strip() or None,
        compute_sha256=args.compute_sha256,
        total_iterations=args.total_iterations,
        chunk_iterations=args.chunk_iterations,
        command_timeout_seconds=args.command_timeout,
        max_resume_attempts=args.max_resume_attempts,
    )
    try:
        path = FilesystemJobSpool(work_dir).submit(spec)
    except (FileExistsError, ProtocolValidationError, OSError) as exc:
        print(f"Job submission failed: {exc}", file=sys.stderr)
        return 1

    print(f"Submitted {spec.stage_type} job {spec.job_id}")
    print(f"Incoming file: {path}")
    print(f"Expected worker boot ID: {spec.expected_worker_boot_id}")
    print(f"Expected Fluent generation: {spec.expected_fluent_generation}")
    if spec.case_path is not None:
        print(f"Requested case path: {spec.case_path}")
    if spec.stage_type == "resumable_run":
        print(f"Iteration target: {spec.total_iterations}")
        print(f"Checkpoint chunk: {spec.chunk_iterations}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
