; Bounded file reader. read-char/eof-object? are verified Fluent transfer primitives.
(define (p9-line p)
  (let loop ((chars '()) (count 0))
    (if (> count 8192) (error "Phase 9 monitor line exceeds bound")
        (let ((c (read-char p)))
          (cond ((eof-object? c) (if (null? chars) c (list->string (reverse chars))))
                ((char=? c #\newline) (list->string (reverse chars)))
                (else (loop (cons c chars) (+ count 1))))))))
(define (p9-rows path)
  (let ((p (open-input-file path)))
    (let loop ((rows '()) (count 0))
      (if (> count 100000) (error "Phase 9 monitor file exceeds bound")
      (let ((line (p9-line p)))
        (if (eof-object? line)
            (begin (close-input-port p) rows)
            (let* ((q (open-input-string line)) (a (read q))
                   (b (if (number? a) (read q) #f)))
              (close-input-port q)
              (loop (if (and (number? a) (number? b))
                        (cons (cons a b) rows) rows) (+ count 1)))))))))
(define (p9-values path lo hi)
  (let ((rows (p9-rows path)))
    (let loop ((i lo) (values '()))
      (if (> i hi) (reverse values)
          (let ((entry (assoc i rows)))
            (if (and entry (<= (abs (cdr entry)) 1e100))
                (loop (+ i 1) (cons (cdr entry) values))
                (error "Missing or nonfinite Phase 9 monitor value" i)))))))
(define (p9-range values denominator)
  (/ (* 100.0 (- (apply max values) (apply min values)))
     (max (abs denominator) 1e-12)))
(define (p9-mean values) (/ (apply + values) (length values)))
